
#!/bin/bash

echo "----------------------------"
echo "----- ImageMagick Menu -----"
echo "----------------------------"
echo "--- konverze obrazku 1) ----"
echo "----- zmena kvality 2) -----"
echo "----- zmena rozmeru 3) -----"
echo "---- otoceni obrazku 4) ----"
echo "-------- efekty 5) ---------"
echo "----------------------------"
echo ""
echo "----------------------------"
echo "----- Chcete upravovat -----"
echo "--- soubor nebo adresar? ---"
echo "----------------------------"
echo "-------- adresar 1) --------"
echo "-------- soubor 2) ---------"
echo "----------------------------"
echo ""
echo "----------------------------"
echo "----- Zadejte cestu k ------"
echo "----- adresari/souboru -----"
echo "----------------------------"
echo "-------- Napriklad: --------"
echo "--/home/user/picture.png ---"
echo "----/home/user/pictures ----"
echo "----------------------------"
echo "-------Zadejte cestu--------" 
echo "---- k souboru/adresari ----"
echo ""
echo "------------------------------"
echo "--Konverze do jineho formatu--"
echo "------------------------------"
echo "------- JPG --> PNG 1) -------"
echo "------- PNG --> JPG 2) -------"
echo "------------------------------"

